<?php
$carz_slider_sc = carz_get_theme_option( 'front_page_title_shortcode' );
if ( ! empty( $carz_slider_sc ) && strpos( $carz_slider_sc, '[' ) !== false && strpos( $carz_slider_sc, ']' ) !== false ) {

	?><div class="front_page_section front_page_section_title front_page_section_slider front_page_section_title_slider
		<?php
		if ( carz_get_theme_option( 'front_page_title_stack' ) ) {
			echo ' sc_stack_section_on';
		}
		?>
	">
	<?php
		// Add anchor
		$carz_anchor_icon = carz_get_theme_option( 'front_page_title_anchor_icon' );
		$carz_anchor_text = carz_get_theme_option( 'front_page_title_anchor_text' );
	if ( ( ! empty( $carz_anchor_icon ) || ! empty( $carz_anchor_text ) ) && shortcode_exists( 'trx_sc_anchor' ) ) {
		echo do_shortcode(
			'[trx_sc_anchor id="front_page_section_title"'
									. ( ! empty( $carz_anchor_icon ) ? ' icon="' . esc_attr( $carz_anchor_icon ) . '"' : '' )
									. ( ! empty( $carz_anchor_text ) ? ' title="' . esc_attr( $carz_anchor_text ) . '"' : '' )
									. ']'
		);
	}
		// Show slider (or any other content, generated by shortcode)
		echo do_shortcode( $carz_slider_sc );
	?>
	</div>
	<?php

} else {

	?>
	<div class="front_page_section front_page_section_title
		<?php
		$carz_scheme = carz_get_theme_option( 'front_page_title_scheme' );
		if ( ! empty( $carz_scheme ) && ! carz_is_inherit( $carz_scheme ) ) {
			echo ' scheme_' . esc_attr( $carz_scheme );
		}
		echo ' front_page_section_paddings_' . esc_attr( carz_get_theme_option( 'front_page_title_paddings' ) );
		if ( carz_get_theme_option( 'front_page_title_stack' ) ) {
			echo ' sc_stack_section_on';
		}
		?>
		"
		<?php
		$carz_css      = '';
		$carz_bg_image = carz_get_theme_option( 'front_page_title_bg_image' );
		if ( ! empty( $carz_bg_image ) ) {
			$carz_css .= 'background-image: url(' . esc_url( carz_get_attachment_url( $carz_bg_image ) ) . ');';
		}
		if ( ! empty( $carz_css ) ) {
			echo ' style="' . esc_attr( $carz_css ) . '"';
		}
		?>
	>
	<?php
		// Add anchor
		$carz_anchor_icon = carz_get_theme_option( 'front_page_title_anchor_icon' );
		$carz_anchor_text = carz_get_theme_option( 'front_page_title_anchor_text' );
	if ( ( ! empty( $carz_anchor_icon ) || ! empty( $carz_anchor_text ) ) && shortcode_exists( 'trx_sc_anchor' ) ) {
		echo do_shortcode(
			'[trx_sc_anchor id="front_page_section_title"'
									. ( ! empty( $carz_anchor_icon ) ? ' icon="' . esc_attr( $carz_anchor_icon ) . '"' : '' )
									. ( ! empty( $carz_anchor_text ) ? ' title="' . esc_attr( $carz_anchor_text ) . '"' : '' )
									. ']'
		);
	}
	?>
		<div class="front_page_section_inner front_page_section_title_inner
		<?php
		if ( carz_get_theme_option( 'front_page_title_fullheight' ) ) {
			echo ' carz-full-height sc_layouts_flex sc_layouts_columns_middle';
		}
		?>
			"
			<?php
			$carz_css      = '';
			$carz_bg_mask  = carz_get_theme_option( 'front_page_title_bg_mask' );
			$carz_bg_color_type = carz_get_theme_option( 'front_page_title_bg_color_type' );
			if ( 'custom' == $carz_bg_color_type ) {
				$carz_bg_color = carz_get_theme_option( 'front_page_title_bg_color' );
			} elseif ( 'scheme_bg_color' == $carz_bg_color_type ) {
				$carz_bg_color = carz_get_scheme_color( 'bg_color', $carz_scheme );
			} else {
				$carz_bg_color = '';
			}
			if ( ! empty( $carz_bg_color ) && $carz_bg_mask > 0 ) {
				$carz_css .= 'background-color: ' . esc_attr(
					1 == $carz_bg_mask ? $carz_bg_color : carz_hex2rgba( $carz_bg_color, $carz_bg_mask )
				) . ';';
			}
			if ( ! empty( $carz_css ) ) {
				echo ' style="' . esc_attr( $carz_css ) . '"';
			}
			?>
		>
			<div class="front_page_section_content_wrap front_page_section_title_content_wrap content_wrap">
				<?php
				// Caption
				$carz_caption = carz_get_theme_option( 'front_page_title_caption' );
				if ( ! empty( $carz_caption ) || ( current_user_can( 'edit_theme_options' ) && is_customize_preview() ) ) {
					?>
					<h1 class="front_page_section_caption front_page_section_title_caption front_page_block_<?php echo ! empty( $carz_caption ) ? 'filled' : 'empty'; ?>"><?php echo wp_kses( $carz_caption, 'carz_kses_content' ); ?></h1>
					<?php
				}

				// Description (text)
				$carz_description = carz_get_theme_option( 'front_page_title_description' );
				if ( ! empty( $carz_description ) || ( current_user_can( 'edit_theme_options' ) && is_customize_preview() ) ) {
					?>
					<div class="front_page_section_description front_page_section_title_description front_page_block_<?php echo ! empty( $carz_description ) ? 'filled' : 'empty'; ?>"><?php echo wp_kses( wpautop( $carz_description ), 'carz_kses_content' ); ?></div>
					<?php
				}

				// Buttons
				if ( carz_get_theme_option( 'front_page_title_button1_link' ) != '' || carz_get_theme_option( 'front_page_title_button2_link' ) != '' ) {
					?>
					<div class="front_page_section_buttons front_page_section_title_buttons">
					<?php
						carz_show_layout( carz_customizer_partial_refresh_front_page_title_button1_link() );
						carz_show_layout( carz_customizer_partial_refresh_front_page_title_button2_link() );
					?>
					</div>
					<?php
				}
				?>
			</div>
		</div>
	</div>
	<?php
}
